void Background()
{
	window(1,1,80,25);
	textbackground(WHITE);
	clrscr();
}

void Information_Page();
void Log_In_Page();
void Administrator();
void User();
void Main_Menu();
void New_Marksheet();
void More_Choice();
void See_Now();
void Delete();
void Update();
void All_Records();
void See_Marksheets();
void Error_Window();
void Save_Data();
void Reading_Data();
void Get_Data();
void Put_Marksheet();
void Marksheet();
void Put_Data();
void Set_Admin_Account();
void Login_Again();
void Change_UserName();
void Change_Password();
void if_Condition_False();